// <auto-generated />
using System;
using BaoBoi.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaoBoi.Data.Migrations
{
    [DbContext(typeof(BaoBoiDbContext))]
    [Migration("20210131154714_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BaoBoi.Data.Entities.LoiChuc", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("CauChuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CauChuc");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("ID");

                    b.ToTable("LoiChuc");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CauChuc = "Mừng 2021 phát tài phát lộc. Tiền vô xồng xộc, tiền ra từ từ. Sức khỏe có dư, công danh tấn tới. Tình duyên phơi phới,hạnh phúc thăng hoa.Xin chúc mọi nhà một năm đại thắng.",
                            Type = 0
                        },
                        new
                        {
                            ID = 2,
                            CauChuc = "Năm mới đã tới thật gần, chúc cho đại gia đình một năm mới An Khang Thịnh Vượng",
                            Type = 0
                        },
                        new
                        {
                            ID = 3,
                            CauChuc = "Năm mới với bao điều thú vị đang đến với bạn. Chúc bạn có đủ niềm đam mê để khám phá và tận hưởng từng ngày tươi đẹp của cuộc sống mới",
                            Type = 0
                        },
                        new
                        {
                            ID = 4,
                            CauChuc = "Tết đến, xuân về, an khang thịnh vượng, phát tài phát lộc, sức khỏe dồi dào, mọi điều như ý",
                            Type = 0
                        },
                        new
                        {
                            ID = 5,
                            CauChuc = "Chúc mọi người năm mới An khang thịnh vượng, tài lộc đầy nhà, con cháu sum vầy, một năm bình an và sung túc",
                            Type = 0
                        },
                        new
                        {
                            ID = 6,
                            CauChuc = "Có thể những niềm vui của năm mới kéo dài mãi mãi trong cuộc sống của bạn. Có thể bạn sẽ tìm thấy được ánh sáng dẫn bạn đến thành công, cái đích mà bạn mong muốn. Chúc mừng năm mới",
                            Type = 0
                        },
                        new
                        {
                            ID = 7,
                            CauChuc = "Hãy cùng vẫy tay tạm biệt năm cũ, đón nhận năm mới với nhiều ước mơ, hoài bão và cả hy vọng. Chúc bạn năm mới tràn ngập niềm vui và hạnh phúc",
                            Type = 0
                        },
                        new
                        {
                            ID = 8,
                            CauChuc = "May all your new year wishes come true",
                            Type = 0
                        },
                        new
                        {
                            ID = 9,
                            CauChuc = "Best wishes for a happy and successful new year",
                            Type = 0
                        },
                        new
                        {
                            ID = 10,
                            CauChuc = "Wishing you all the magic of the new year",
                            Type = 0
                        },
                        new
                        {
                            ID = 11,
                            CauChuc = "Let your spirit soar and have a joy-filled new year",
                            Type = 0
                        });
                });

            modelBuilder.Entity("BaoBoi.Data.Entities.PhoneUser", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("Phone");

                    b.Property<double?>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("DatePay")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePay");

                    b.Property<DateTime?>("DatePlay")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePlay");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<bool>("Pay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Pay");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Phone");

                    b.ToTable("PhoneUser");

                    b.HasData(
                        new
                        {
                            Phone = "0967738406",
                            Amount = 0.0,
                            Name = "Admin",
                            Pay = false,
                            Type = 5
                        },
                        new
                        {
                            Phone = "0903754094",
                            Amount = 0.0,
                            Name = "Anh Bình CIMB",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0901239894",
                            Amount = 0.0,
                            Name = "Anh Doanh CIMB",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0967440028",
                            Amount = 0.0,
                            Name = "Anh Đức Anh",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0907603537",
                            Amount = 0.0,
                            Name = "Anh Hiếu CIMB",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0332160345",
                            Amount = 0.0,
                            Name = "Anh Hoà",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0775080990",
                            Amount = 0.0,
                            Name = "Anh khải",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0327489656",
                            Amount = 0.0,
                            Name = "Anh Nguyên",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0355559738",
                            Amount = 0.0,
                            Name = "Anh Nhanh",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0935201352",
                            Amount = 0.0,
                            Name = "Anh Quân",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0908233009",
                            Amount = 0.0,
                            Name = "Anh Thi",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0962857858",
                            Amount = 0.0,
                            Name = "Anh Trung Design",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0982848104",
                            Amount = 0.0,
                            Name = "Ba",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0912520927",
                            Amount = 0.0,
                            Name = "Bà Nội",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0359271374",
                            Amount = 0.0,
                            Name = "Bảo Bối",
                            Pay = false,
                            Type = 5
                        },
                        new
                        {
                            Phone = "0912298018",
                            Amount = 0.0,
                            Name = "Bò",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0986522539",
                            Amount = 0.0,
                            Name = "Cậu Tèo",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0388915223",
                            Amount = 0.0,
                            Name = "Chị Châm",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0397667520",
                            Amount = 0.0,
                            Name = "Chị Dung",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0397280420",
                            Amount = 0.0,
                            Name = "Chị Giàu",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0909047892",
                            Amount = 0.0,
                            Name = "Chị Lành Enrich",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0342103967",
                            Amount = 0.0,
                            Name = "Chị Mai Anh",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0354755733",
                            Amount = 0.0,
                            Name = "Chị Phiên",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0909820075",
                            Amount = 0.0,
                            Name = "Chị Phương Anh",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0396813296",
                            Amount = 0.0,
                            Name = "Chị Thảo Vy",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0908991164",
                            Amount = 0.0,
                            Name = "Chị Thúy Vy",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0925347343",
                            Amount = 0.0,
                            Name = "Chị Trâm",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0329613873",
                            Amount = 0.0,
                            Name = "Chị Trang",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0933184113",
                            Amount = 0.0,
                            Name = "Chị Trinh",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0968338488",
                            Amount = 0.0,
                            Name = "Chị Trinh",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0372303720",
                            Amount = 0.0,
                            Name = "Chong Yau CIMB",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0383539845",
                            Amount = 0.0,
                            Name = "Chức",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0984903994",
                            Amount = 0.0,
                            Name = "Chức",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0327370037",
                            Amount = 0.0,
                            Name = "Cô Dung",
                            Pay = false,
                            Type = 3
                        },
                        new
                        {
                            Phone = "0975723759",
                            Amount = 0.0,
                            Name = "Cô Nhung Trọ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0938091809",
                            Amount = 0.0,
                            Name = "Cô Sương - PLS",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0979224841",
                            Amount = 0.0,
                            Name = "Cô Trinh",
                            Pay = false,
                            Type = 3
                        },
                        new
                        {
                            Phone = "0963463845",
                            Amount = 0.0,
                            Name = "Đại",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0989040813",
                            Amount = 0.0,
                            Name = "Đăng Phúc",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0568200441",
                            Amount = 0.0,
                            Name = "Dat La",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0378109170",
                            Amount = 0.0,
                            Name = "Đẹt",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0776611227",
                            Amount = 0.0,
                            Name = "Dì Chúc",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0386884721",
                            Amount = 0.0,
                            Name = "Duyên",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0358050165",
                            Amount = 0.0,
                            Name = "Duyên",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0373514988",
                            Amount = 0.0,
                            Name = "Gấm",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0378015202",
                            Amount = 0.0,
                            Name = "Hí",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0327141466",
                            Amount = 0.0,
                            Name = "Hí",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0337253858",
                            Amount = 0.0,
                            Name = "Hí",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0978374265",
                            Amount = 0.0,
                            Name = "Hiệp",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0962957940",
                            Amount = 0.0,
                            Name = "Hoàng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0339610931",
                            Amount = 0.0,
                            Name = "Hoàng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0563419551",
                            Amount = 0.0,
                            Name = "Hợi",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0394137496",
                            Amount = 0.0,
                            Name = "Hợi",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0916789498",
                            Amount = 0.0,
                            Name = "Hợi",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0976016307",
                            Amount = 0.0,
                            Name = "Hồng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0367257428",
                            Amount = 0.0,
                            Name = "Hương",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0339427771",
                            Amount = 0.0,
                            Name = "Huyền Đen",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0386586120",
                            Amount = 0.0,
                            Name = "Ka Ram",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0774992232",
                            Amount = 0.0,
                            Name = "Lê Thịnh",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0354171005",
                            Amount = 0.0,
                            Name = "Lu",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0359516706",
                            Amount = 0.0,
                            Name = "Mẹ",
                            Pay = false,
                            Type = 4
                        },
                        new
                        {
                            Phone = "0329003084",
                            Amount = 0.0,
                            Name = "Mỹ Thanh",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0375188165",
                            Amount = 0.0,
                            Name = "Mỹ Thanh",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0332263410",
                            Amount = 0.0,
                            Name = "Ngân Muội",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0969853537",
                            Amount = 0.0,
                            Name = "Nghĩa",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0986839804",
                            Amount = 0.0,
                            Name = "Nghĩa",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0374094726",
                            Amount = 0.0,
                            Name = "Ngoan",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0388855622",
                            Amount = 0.0,
                            Name = "Nhật",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0934452821",
                            Amount = 0.0,
                            Name = "Nhật",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0327090718",
                            Amount = 0.0,
                            Name = "Nhung",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0349925559",
                            Amount = 0.0,
                            Name = "Oanh Cao",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0978939976",
                            Amount = 0.0,
                            Name = "Phạm Linh Linh",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0978225695",
                            Amount = 0.0,
                            Name = "Phú",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0333262399",
                            Amount = 0.0,
                            Name = "Quân",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0394204227",
                            Amount = 0.0,
                            Name = "Quốc Hưng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0354023098",
                            Amount = 0.0,
                            Name = "Quốc Thông",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0929207097",
                            Amount = 0.0,
                            Name = "Quốc Thông",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0375767266",
                            Amount = 0.0,
                            Name = "Quyền",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0396513565",
                            Amount = 0.0,
                            Name = "Sáng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0962744683",
                            Amount = 0.0,
                            Name = "Sơn Xù",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "60162175578",
                            Amount = 0.0,
                            Name = "Stephen",
                            Pay = false,
                            Type = 1
                        },
                        new
                        {
                            Phone = "0354601772",
                            Amount = 0.0,
                            Name = "Sumi",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0989538072",
                            Amount = 0.0,
                            Name = "Sven",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0349548560",
                            Amount = 0.0,
                            Name = "Sỹ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "1",
                            Amount = 0.0,
                            Name = "Test",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0969102120",
                            Amount = 0.0,
                            Name = "Thái",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0342829455",
                            Amount = 0.0,
                            Name = "Thảo",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0914290456",
                            Amount = 0.0,
                            Name = "Thầy Lộc",
                            Pay = false,
                            Type = 3
                        },
                        new
                        {
                            Phone = "0908202983",
                            Amount = 0.0,
                            Name = "Thầy Vĩnh",
                            Pay = false,
                            Type = 3
                        },
                        new
                        {
                            Phone = "0382115375",
                            Amount = 0.0,
                            Name = "Thịnh",
                            Pay = false,
                            Type = 2
                        },
                        new
                        {
                            Phone = "0976393245",
                            Amount = 0.0,
                            Name = "Thơ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0989764925",
                            Amount = 0.0,
                            Name = "Thu Trang",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0332950027",
                            Amount = 0.0,
                            Name = "Thuận",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0363944069",
                            Amount = 0.0,
                            Name = "Thuý",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0388825432",
                            Amount = 0.0,
                            Name = "Thuý",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0329979306",
                            Amount = 0.0,
                            Name = "Thuý",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0968113772",
                            Amount = 0.0,
                            Name = "Thuý",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0369712191",
                            Amount = 0.0,
                            Name = "Tô Bướm",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0986179154",
                            Amount = 0.0,
                            Name = "Toàn",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0367816473",
                            Amount = 0.0,
                            Name = "Tráng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0376545320",
                            Amount = 0.0,
                            Name = "Tráng",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0966785834",
                            Amount = 0.0,
                            Name = "Trang Tuyền",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0348879740",
                            Amount = 0.0,
                            Name = "Trí Thông",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0394959832",
                            Amount = 0.0,
                            Name = "Trinh Toeic",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0376093038",
                            Amount = 0.0,
                            Name = "Tường Vi",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0566820006",
                            Amount = 0.0,
                            Name = "Ù",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0987221504",
                            Amount = 0.0,
                            Name = "Ursa",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0978086565",
                            Amount = 0.0,
                            Name = "Vân Muội Muội",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0399658291",
                            Amount = 0.0,
                            Name = "Vĩ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0377377487",
                            Amount = 0.0,
                            Name = "Vĩ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0376463339",
                            Amount = 0.0,
                            Name = "Vũ",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0886525647",
                            Amount = 0.0,
                            Name = "Vũ Đạt",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0968270836",
                            Amount = 0.0,
                            Name = "Vũ Linh",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0977811837",
                            Amount = 0.0,
                            Name = "Xuân",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0353264570",
                            Amount = 0.0,
                            Name = "Xuân Nam",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0163673765",
                            Amount = 0.0,
                            Name = "Yee Kuan",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0368013361",
                            Amount = 0.0,
                            Name = "Yến",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "0388991387",
                            Amount = 0.0,
                            Name = "Yến",
                            Pay = false,
                            Type = 0
                        },
                        new
                        {
                            Phone = "60123836370",
                            Amount = 0.0,
                            Name = "Yew Khai Shing",
                            Pay = false,
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
